### **IMPORTANDO LIBRERÍAS**

In [1]:
import numpy as np # el np es un alias del nombre de la biblioteca numpy
import sys # este paquete maneja funciones del sistema, al ser corto no es necesario darle un alias

### **Creando una lista de 10 elementos**

In [21]:
lista1 = list(range(1, 11))
lista1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

### **Transformado la lista a un Array**

recordar que un `array` es una estructura propia de la librería numpy.

In [3]:
arreglo = np.array(lista1)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### **Consultando el tipo de dato númerico del arreglo**

In [4]:
arreglo.dtype

dtype('int64')

### **Crear una lista de solo números uno y cero**



In [5]:
unos = np.ones(100)
unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
ceros = np.zeros(100)
ceros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### **Lista de Datos Compuestos (Transformando a Array)**

In [7]:
lista2 = ['Victor', 2, 5.6, True]
lista2

['Victor', 2, 5.6, True]

### **Transformando la lista en Array**

In [8]:
arreglo2 = np.array(lista2)
arreglo2

array(['Victor', '2', '5.6', 'True'], dtype='<U32')

### **Consultando la cantidad de memoria ocupada por estructura (Paquete Sys)**

In [9]:
memoria_lista = sys.getsizeof(lista1)
memoria_arreglo = arreglo.nbytes

print(f"Memoria ocupada por la lista: {memoria_lista} bytes")
print(f"Memoria ocupada por el array: {memoria_arreglo} bytes")

Memoria ocupada por la lista: 136 bytes
Memoria ocupada por el array: 80 bytes


### **Otros métodos de Numpy**

In [10]:
print("Shape:", arreglo.shape)         # Dimensiones
print("Dimensiones:", arreglo.ndim)    # Número de ejes
print("Tamaño:", arreglo.size)         # Tipo de Tamaño
print("Tipo de Dato:", arreglo.dtype)  # Tamaño de almacenamiento
print("Bytes/elem:", arreglo.itemsize) # Tamaño en bytes de cada elemento

Shape: (10,)
Dimensiones: 1
Tamaño: 10
Tipo de Dato: int64
Bytes/elem: 8


### **Obteniendo el Promedio del Arreglo**

In [23]:
promedio = np.mean(lista1)
promedio

np.float64(5.5)

### **Transformando el Arreglo de Int a Float**

El método astype() transforma los elementos

In [25]:
new_arreglo = arreglo.astype(np.float16) # Se puede especificar el tipo de n° flotante (float16, float32, float64, etc.)
new_arreglo

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float16)

### **Aplicando el Paquete Random**

Se genera una lista de números enteros aleatorios, que van del 1 al 100

In [13]:
np.random.rand() # genera números aleatorios del rango [0,1]

0.6179311134371126

In [14]:
np.random.rand(5) # genera números aleatorios del rango [0,1], pero en este caso n cantidad

array([0.86077363, 0.73939963, 0.18510261, 0.03939762, 0.61357965])

In [15]:
np.random.randint(10) # genera números enteros aleatorios del rango [1,10]

4

In [16]:
np.random.rand(1, 10, 4) # genera números aleatorios del rango [0,1], en este caso como una matriz de números, generando columnas

array([[[0.61884504, 0.18645726, 0.19989626, 0.97502397],
        [0.27015497, 0.92806036, 0.07670052, 0.16007426],
        [0.49943785, 0.24297855, 0.0943347 , 0.37362899],
        [0.0382593 , 0.29569308, 0.19165235, 0.36903841],
        [0.76980048, 0.3491715 , 0.15460117, 0.42550097],
        [0.50143994, 0.32955008, 0.39172174, 0.48086716],
        [0.39298557, 0.56028245, 0.80885791, 0.35980409],
        [0.03478815, 0.31203067, 0.34968499, 0.16828456],
        [0.84334006, 0.35372987, 0.67569472, 0.5750583 ],
        [0.65919124, 0.61978975, 0.94005994, 0.83961385]]])

In [ ]:
np.random.randint(1, 100, 10) # generando 10 números aleatorios del 1 al 100
                              # El 1 representa el rango minimo y el 100 el rango maximo, mientras que el 10 es la cantidad de veces que genera estos números

array([ 4, 96, 73, 88, 93, 21, 60, 81, 36, 93], dtype=int32)

### **Método Arange**

In [18]:
arreglo3 = np.arange(1,11)
arreglo3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])